# Definitions at https://github.com/DioxusLabs/cli/blob/master/docs/src/configure.md

[application]
name = "desktop-dashboard"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "dashboard"

[web.watcher]
reload_html = true
watch_path = ["src", "public"]
index_on_404 = true

[web.resource]
style = []
script = []

[web.resource.dev]
script = []

[application.tools]
binaryen = { wasm_opt = true }
